name: Build Android (Debug APK)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: "17" }
      - uses: android-actions/setup-android@v4
      - name: Install SDK components
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses
      - uses: gradle/actions/setup-gradle@v4
        with: { gradle-version: "8.4.2" }
      - name: Generate wrapper
        run: gradle wrapper --gradle-version 8.4.2
      - name: Build Debug
        run: ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
